In [11]:
from pathlib import Path
import pandas as pd
import json
import pandas as pd

In [ ]:
"""WORKING"""
DATA_DIR = Path("C:/Users/felix.mcdonald/Projects/regent/regents_gate_reports/data/raw")

def load_financials():
    records = {}
    for file in (DATA_DIR / "financial_statements").glob("*.xlsx"):
        records[file.stem] = pd.read_excel(file, sheet_name=None)  # dict of DataFrames
    return records

In [13]:
df = load_financials()

In [ ]:
df

98

Below script processes the Excel file for a given company and saves quarterly financial data to a CSV file.
It compares company file with financial_statements

In [18]:
from pathlib import Path
import pandas as pd
import re

def extract_quarter_key(sheet_name):
    """
    Converts sheet names like 'Q2 2021' into a (year, quarter) tuple for sorting.
    """
    match = re.match(r"Q(\d)\s+(\d{4})", sheet_name)
    if match:
        q, y = match.groups()
        return int(y), int(q)
    return (0, 0)

def process_financials(company_name, 
                       raw_dir,
                       #out_dir=Path("data/processed")
                       ):
    """
    Processes the Excel file for a given company and saves quarterly financial data to a CSV file.
    """
    file_path = raw_dir / f"{company_name}.xlsx"
    if not file_path.exists():
        return None

    try:
        sheet_dict = pd.read_excel(file_path, sheet_name=None)
    except Exception:
        return None

    sorted_sheets = sorted(sheet_dict.items(), key=lambda x: extract_quarter_key(x[0]))

    records = []
    for sheet_name, df in sorted_sheets:
        try:
            temp = df.set_index(df.columns[0]).T
            temp["quarter"] = sheet_name
            temp["company"] = company_name
            records.append(temp)
        except Exception:
            continue

    if not records:
        return None

    result_df = pd.concat(records, ignore_index=True)

    # company_dir = out_dir / company_name
    # company_dir.mkdir(parents=True, exist_ok=True)
    # result_df.to_csv(company_dir / "financials.csv", index=False)

    return result_df

In [20]:
result_df = process_financials(company_name='Johnson-Thompson', 
                               raw_dir=Path("C:/Users/felix.mcdonald/Projects/regent/regents_gate_reports/data/raw/financial_statements"),
                               # out_dir=Path("data/processed")
                                )

In [22]:
result_df

Unnamed: 0,revenue,expenses,net_income,assets,liabilities,equity,cash,debt,equity_ratio,debt_ratio,quarter,company
0,68,72,86,25,13,32,22,37,17,10,Q1 2020,Johnson-Thompson
1,27,39,64,77,47,42,33,72,73,7,Q2 2020,Johnson-Thompson
2,32,15,91,40,40,3,36,18,31,32,Q3 2020,Johnson-Thompson
3,43,98,43,73,95,88,54,15,90,83,Q4 2020,Johnson-Thompson
4,22,90,6,47,19,37,46,45,91,68,Q1 2021,Johnson-Thompson
5,26,16,22,81,40,28,87,9,75,14,Q2 2021,Johnson-Thompson
6,3,30,19,48,15,65,51,40,16,15,Q3 2021,Johnson-Thompson
7,83,42,20,20,50,17,25,64,14,82,Q4 2021,Johnson-Thompson
8,45,42,47,16,79,6,67,4,31,27,Q1 2022,Johnson-Thompson
9,13,14,86,14,48,80,8,43,31,59,Q2 2022,Johnson-Thompson
10,98,13,14,91,99,56,84,93,35,76,Q3 2022,Johnson-Thompson
11,41,64,82,51,50,49,20,50,36,92,Q4 2022,Johnson-Thompson
12,18,47,37,53,29,10,85,51,53,59,Q1 2023,Johnson-Thompson
13,78,21,63,21,27,30,22,81,76,67,Q2 2023,Johnson-Thompson
14,29,77,5,41,98,77,80,34,31,62,Q3 2023,Johnson-Thompson
15,33,47,57,71,83,29,18,80,64,32,Q4 2023,Johnson-Thompson
16,78,12,9,2,87,51,43,5,12,59,Q1 2024,Johnson-Thompson
17,55,41,78,71,20,97,27,70,16,7,Q2 2024,Johnson-Thompson
18,10,20,13,44,22,11,27,45,70,54,Q3 2024,Johnson-Thompson
19,30,81,90,61,85,61,18,91,23,46,Q4 2024,Johnson-Thompson
20,55,6,9,14,93,11,52,45,2,30,Q1 2025,Johnson-Thompson